### Spam Filter

In [29]:
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

messages = pd.read_csv("SMSSpamCollection", sep="\t", names=["label","message"])

corpus = []
for i in range(len(messages)):
    review = re.sub('^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(w) for w in review if w not in stop_words]
    review = " ".join(review)
    corpus.append(review)

    
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
cv = CountVectorizer(max_features =5000)
x = cv.fit_transform(corpus).toarray()

y = pd.get_dummies(messages['label'])
y = y.iloc[:,1].values
print(y)
print(x)

 
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.20,random_state=0)

from sklearn.naive_bayes import MultinomialNB
span_detect_model = MultinomialNB().fit(x_train, y_train)

y_predict = span_detect_model.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
conf_matrix = confusion_matrix(y_test,y_predict)
accuracy =accuracy_score(y_test,y_predict)
accuracy


[0 0 1 ... 0 0 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.9874439461883409