### WordEmbedding Technique usinng Embedding Layer in Keras


In [5]:
from tensorflow.keras.preprocessing.text import one_hot


In [6]:
sent = ["the glass of water",
       "the cup of tea",
       "I am good boy",
       "I am a good developer",
       "Every problem have solution",
       "finding the way towards the success"]
sent

['the glass of water',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'Every problem have solution',
 'finding the way towards the success']

### One Hot representation

In [7]:
# Vocubulary size
voc_size = 10000

In [9]:
one_hot_repr = [one_hot(word, voc_size) for word in sent]
print(one_hot_repr)

[[779, 1974, 8704, 9037], [779, 1815, 8704, 6868], [4715, 9789, 7115, 1944], [4715, 9789, 7281, 7115, 1379], [5112, 5627, 1865, 9106], [3312, 779, 8835, 2304, 779, 5863]]


#### Word Embeding Represention

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [17]:
# Add pading sentences to maximum lenght of sentence
sent_length = 6
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0  779 1974 8704 9037]
 [   0    0  779 1815 8704 6868]
 [   0    0 4715 9789 7115 1944]
 [   0 4715 9789 7281 7115 1379]
 [   0    0 5112 5627 1865 9106]
 [3312  779 8835 2304  779 5863]]


In [19]:
# embeding layer
dim =10
model = Sequential()
model.add(Embedding(voc_size,10, input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 6, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
print(model.predict(embedded_docs))

[[[ 2.80183591e-02  4.10819165e-02  2.85612233e-02 -2.69489419e-02
    2.91073434e-02  1.82433017e-02 -4.44082282e-02 -1.65144429e-02
    3.78654264e-02  3.55231874e-02]
  [ 2.80183591e-02  4.10819165e-02  2.85612233e-02 -2.69489419e-02
    2.91073434e-02  1.82433017e-02 -4.44082282e-02 -1.65144429e-02
    3.78654264e-02  3.55231874e-02]
  [-3.51622216e-02  3.15159075e-02  2.74468325e-02  1.68078281e-02
    3.25014926e-02 -2.60196086e-02 -1.96573138e-02 -2.21291780e-02
   -1.78514346e-02  1.10758319e-02]
  [-2.76598688e-02 -2.73043402e-02 -1.40092745e-02 -3.84107940e-02
   -2.57722978e-02 -3.95131595e-02 -1.20117180e-02  2.89455391e-02
    4.40716743e-03  4.76131774e-02]
  [-3.84116173e-03  1.33605115e-02  4.85220291e-02 -3.99181619e-02
    4.50921766e-02 -3.35217491e-02 -1.82489641e-02  3.76754887e-02
    7.48664141e-03  2.38970667e-03]
  [-3.30133922e-02 -4.88150977e-02  3.78603004e-02 -3.24671753e-02
    4.59316112e-02  1.97702646e-03 -2.48072278e-02 -2.06227433e-02
   -7.41682947e-

In [21]:
embedded_docs[0]

array([   0,    0,  779, 1974, 8704, 9037], dtype=int32)

In [22]:
# embedding matrix
print(model.predict(embedded_docs)[0])

[[ 0.02801836  0.04108192  0.02856122 -0.02694894  0.02910734  0.0182433
  -0.04440823 -0.01651444  0.03786543  0.03552319]
 [ 0.02801836  0.04108192  0.02856122 -0.02694894  0.02910734  0.0182433
  -0.04440823 -0.01651444  0.03786543  0.03552319]
 [-0.03516222  0.03151591  0.02744683  0.01680783  0.03250149 -0.02601961
  -0.01965731 -0.02212918 -0.01785143  0.01107583]
 [-0.02765987 -0.02730434 -0.01400927 -0.03841079 -0.0257723  -0.03951316
  -0.01201172  0.02894554  0.00440717  0.04761318]
 [-0.00384116  0.01336051  0.04852203 -0.03991816  0.04509218 -0.03352175
  -0.01824896  0.03767549  0.00748664  0.00238971]
 [-0.03301339 -0.0488151   0.0378603  -0.03246718  0.04593161  0.00197703
  -0.02480723 -0.02062274 -0.00074168 -0.01074915]]
